```{r, setup}
library(rgl)
library(MASS)
```

Make a cloud like a doughnut with icing and sprinkles.  

```{r}
# first layer
muC1 <- c(0,0,0)
covmatC1 <- diag(c(2,2,0.04))
C1 <- as.data.frame(mvrnorm(10000,muC1,covmatC1))
colnames(C1) <- c('x','y','z')
C1hole <- subset(C1, (x^2+y^2)>1.7 & (x^2+y^2)<7)
# second layer
muC2 <- c(0,0,0.8)
covmatC2 <- diag(c(2,2,0.01))
C2 <- as.data.frame(mvrnorm(10000,muC2,covmatC2))
colnames(C2) <- c('x','y','z')
C2hole <- subset(C2, (x^2+y^2)>1.7 & (x^2+y^2)<7)
# sprinkles
muC3 <- c(0,0,0.9)
covmatC3 <- diag(c(2,2,0.01))
C_red <- as.data.frame(mvrnorm(100,muC3,covmatC3))
C_blue <- as.data.frame(mvrnorm(100,muC3,covmatC3))
C_yellow <- as.data.frame(mvrnorm(100,muC3,covmatC3))
C_green <- as.data.frame(mvrnorm(100,muC3,covmatC3))
colnames(C_red) <- c('x','y','z')
colnames(C_blue) <- c('x','y','z')
colnames(C_yellow) <- c('x','y','z')
colnames(C_green) <- c('x','y','z')
C3h_r <- subset(C_red, (x^2+y^2)>1.7 & (x^2+y^2)<7)
C3h_b <- subset(C_blue, (x^2+y^2)>1.7 & (x^2+y^2)<7)
C3h_y <- subset(C_yellow, (x^2+y^2)>1.7 & (x^2+y^2)<7)
C3h_g <- subset(C_green, (x^2+y^2)>1.7 & (x^2+y^2)<7)

plot3d(C1hole,type='s',radius = 0.3,col='sienna3',add=T)
plot3d(C2hole,type='s',radius = 0.0999,col='palevioletred1',add=T)
plot3d(C3h_r,type='s',radius = 0.09,col='red',add=T)
plot3d(C3h_b,type='s',radius = 0.09,col='blue',add=T)
plot3d(C3h_y,type='s',radius = 0.09,col='yellow',add=T)
plot3d(C3h_g,type='s',radius = 0.09,col='green',add=T)
rglwidget()
```
